=== bsrpn6/PauloETL/ETLSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2008 (http://www.altova.com) by Stephanie Giovannini (Barry-Wehmiller Design Group) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="root">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="connections">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="connection" type="connection" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="jobs">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="job" type="job" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="connection">
		<xs:attribute name="id" type="xs:string" use="required"/>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="connstring" type="xs:string" use="required"/>
		<xs:attribute name="uid" type="xs:string" use="required"/>
		<xs:attribute name="pwd" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="param">
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="source" type="xs:string" use="required"/>
		<xs:attribute name="type" type="adodatatype" use="required"/>
		<xs:attribute name="direction" type="adoparamdirection" use="required"/>
		<xs:attribute name="size">
			<xs:simpleType>
				<xs:restriction base="xs:integer">
					<xs:minInclusive value="0"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="command" mixed="true">
		<xs:sequence>
			<xs:element name="params">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="param" type="param" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="foreach">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="command" type="command" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="connid" type="xs:string" use="required"/>
		<xs:attribute name="rowset" type="xs:boolean" use="required"/>
		<xs:attribute name="begintran" type="xs:boolean" use="required"/>
		<xs:attribute name="enabled" type="xs:boolean" use="required"/>
	</xs:complexType>
	<xs:complexType name="step">
		<xs:sequence>
			<xs:element name="command" type="command"/>
		</xs:sequence>
		<xs:attribute name="name" use="required"/>
	</xs:complexType>
	<xs:complexType name="job">
		<xs:sequence>
			<xs:element name="step" type="step" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required"/>
		<xs:attribute name="name" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:simpleType name="adodatatype" final="">
		<xs:restriction base="xs:string">
			<xs:whiteSpace value="collapse"/>
			<xs:enumeration value="adboolean"/>
			<xs:enumeration value="adchar"/>
			<xs:enumeration value="addate"/>
			<xs:enumeration value="addouble"/>
			<xs:enumeration value="adinteger"/>
			<xs:enumeration value="advarchar"/>
			<xs:enumeration value="adsingle"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="adoparamdirection">
		<xs:restriction base="xs:string">
			<xs:whiteSpace value="collapse"/>
			<xs:enumeration value="adparaminput"/>
			<xs:enumeration value="adparaminputoutput"/>
			<xs:enumeration value="adparamoutput"/>
			<xs:enumeration value="adparamreturnvalue"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== bsrpn6/PauloETL/PauloETL.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--This File Configures Interface Between Oracle and SQL Server for PauloWIP System.-->
<!--  Rev 1 10/14/2010 Marc Bertrand - Modified to Access New Field For Temper Delay Setting-->
<root xsi:noNamespaceSchemaLocation="ETLSchema.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<connections>
		<connection id="SQL" connstring="Provider='sqloledb';Data Source=STLFTTMA;Initial Catalog=PauloWIP;Persist Security Info=True;User ID=process;Password='process'" name="Paulo Site WIP Database" uid="process" pwd="process"/>
		<connection id="ORACLE" connstring="Provider=OraOLEDB.Oracle;Data Source=STLDAQCR;Persist Security Info=True;User ID=equipdaq;Password=qdaq;Unicode=True" name="Paulo Oracle PICS Database" uid="equipdaq" pwd="qdaq"/>
	</connections>
	<jobs>
		<job id="Main" name="Upload Events and Download Schedule/Shop Order Information From Oracle">
			<step name="Set Oracle Role">
				<command name="Set Oracle Role" rowset="false" begintran="false" connid="ORACLE" enabled="true">
					<!--This Command calls oiBHTSchedCCDownloadStart which Initializes Cost Center for Download -->
					<![CDATA[SET ROLE equipment_user IDENTIFIED BY equipment]]>
					<params/>
					<foreach/>
				</command>
			</step>
			<step name="Upload Events To Oracle">
				<command name="Get Equipment Events To Send" enabled="true" rowset="true" begintran="false" connid="SQL">
					<!--This Command calls oiBHTEquipmentEventsGet which Retrieves Rowset Containing Data Rows to Send To Oracle -->
					<![CDATA[EXEC dbo.oiBHTEquipmentEventsGet]]>
					<params/>
					<foreach>
						<command name="Send Equipment Event To Oracle" enabled="true" rowset="false" begintran="false" connid="ORACLE">
							<!--This Command calls equipdaq.PK_SCHEDULE_IQ_PLC.GetQueue which retrieves data from Oracle -->
							<![CDATA[{call  qdaq$PK_SCHEDULE_IQ_PLC.SendEquipmentEvent (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)}]]>
							<params>
								<param  name="Al_PicsID" source="PICSID" type="adinteger" direction="adparaminput"/>
								<param  name="Al_Schedule" source="ScheduleID" type="adinteger" direction="adparaminput"/>
								<param  name="Al_Subset" source="ScheduleSubSetID" type="adinteger" direction="adparaminput"/>
								<param  name="Al_StepOrder" source="ScheduleDetailStepNum" type="adinteger" direction="adparaminput"/>
								<param  name="Al_Detail" source="ScheduleDetailSeq" type="adinteger" direction="adparaminput"/>
								<param  name="Al_CC" source="CCID" type="adinteger" direction="adparaminput"/>
								<param  name="Adt_Timestamp" source="EventTimeStamp" type="addate" direction="adparaminput"/>
								<param  name="Al_Equiment" source="EquipID" type="adinteger" direction="adparaminput"/>
								<param  name="Al_EventCode" source="OracleEventCode" type="adinteger" direction="adparaminput"/>
								<param  name="Al_Activity" source="ActivityZone" type="adinteger" direction="adparaminput"/>
								<param  name="Al_RecipeType" source="RecipeType" type="adinteger" direction="adparaminput"/>
								<param  name="Al_RecipeTime" source="RecipeTime" type="adinteger" direction="adparaminput"/>
								<param  name="Al_RecipeTemp" source="RecipeTemp" type="adinteger" direction="adparaminput"/>
							</params>
							<foreach>
								<command name="Update Event Row In SQL" enabled="true" rowset="false" begintran="false" connid="SQL">
									<!--This Command calls oiBHTEquipmentEventSent which Updates Row in SQL Server to Mark Success/Failure -->
									<![CDATA[EXEC dbo.oiBHTEquipmentEventSent ?, ?]]>
									<params>
										<param name="OI_EventID" source=".OI_EventID" type="adinteger" direction="adparaminput"/>
										<param name="OracleReturnCode" source="RETURN_CODE" type="adinteger" direction="adparaminput"/>
									</params>
									<foreach/>
								</command>
							</foreach>
						</command>
					</foreach>
				</command>
			</step>
			<step name="Upload Shop Order Weights To Oracle">
				<command name="Get Shop Order Weights To Send" enabled="true" rowset="true" begintran="false" connid="SQL">
					<!--This Command calls oiBHTShopOrderWeightsGet which Retrieves Rowset Containing Data Rows to Send To Oracle -->
					<![CDATA[EXEC dbo.oiBHTShopOrderWeightsGet]]>
					<params/>
					<foreach>
						<command name="Send Shop Order Weight To Oracle" enabled="true" rowset="false" begintran="false" connid="ORACLE">
							<!--This Command calls qdaq$PK_SCHEDULE_IQ_PLC.SetActualWeight to send event to Oracle -->
							<![CDATA[{call  qdaq$PK_SCHEDULE_IQ_PLC.SetActualWeight (?, ?, ?, ?, ?, ?, ?, ?)}]]>
							<params>
								<param  name="Al_Schedule" source="ScheduleID" type="adinteger" direction="adparaminput"/>
								<param  name="Al_Subset" source="ScheduleSubSetID" type="adinteger" direction="adparaminput"/>
								<param  name="Al_PicsID" source="PICSID" type="adinteger" direction="adparaminput"/>
								<param  name="Al_CC" source="CCID" type="adinteger" direction="adparaminput"/>
								<param  name="Al_Equipment" source="EquipID" type="adinteger" direction="adparaminput"/>
								<param  name="Al_ShopOrderID" source="ShopOrderID" type="adinteger" direction="adparaminput"/>
								<param  name="Al_ShopOrderSubsetID" source="ShopOrderSubsetID" type="adinteger" direction="adparaminput"/>
								<param  name="Al_Weight" source="Weight" type="adsingle" direction="adparaminput"/>
							</params>
							<foreach>
								<command name="Update Event Row In SQL" enabled="true" rowset="false" begintran="false" connid="SQL">
									<!--This Command calls oiBHTShopOrderWeightSent which Updates Row in SQL Server to Mark Success/Failure -->
									<![CDATA[EXEC dbo.oiBHTShopOrderWeightSent ?, ?]]>
									<params>
										<param name="OI_EventID" source=".OI_EventID" type="adinteger" direction="adparaminput"/>
										<param name="OracleReturnCode" source="RETURN_CODE" type="adinteger" direction="adparaminput"/>
									</params>
									<foreach/>
								</command>
							</foreach>
						</command>
					</foreach>
				</command>
			</step>
			<step name="Upload Gross Weight To Oracle">
				<command name="Get Gross Weights To Send" enabled="true" rowset="true" begintran="false" connid="SQL">
					<!--This Command calls oiBHTScheduleGrossWeightGet which Retrieves Rowset Containing Data Rows to Send To Oracle -->
					<![CDATA[EXEC dbo.oiBHTScheduleGrossWeightGet]]>
					<params/>
					<foreach>
						<command name="Send Gross Weight To Oracle" enabled="true" rowset="false" begintran="false" connid="ORACLE">
							<!--This Command calls qdaq$PK_SCHEDULE_IQ_PLC.SetActualGrossWeight to send event to Oracle -->
							<![CDATA[{call  qdaq$PK_SCHEDULE_IQ_PLC.SetActualGrossWeight (?, ?, ?, ?, ?, ?)}]]>
							<params>
								<param  name="Al_Schedule" source="ScheduleID" type="adinteger" direction="adparaminput"/>
								<param  name="Al_Subset" source="ScheduleSubSetID" type="adinteger" direction="adparaminput"/>
								<param  name="Al_PicsID" source="PICSID" type="adinteger" direction="adparaminput"/>
								<param  name="Al_CC" source="CCID" type="adinteger" direction="adparaminput"/>
								<param  name="Al_Equipment" source="EquipID" type="adinteger" direction="adparaminput"/>
								<param  name="Al_Weight" source="Weight" type="adsingle" direction="adparaminput"/>
							</params>
							<foreach>
								<command name="Update Event Row In SQL" enabled="true" rowset="false" begintran="false" connid="SQL">
									<!--This Command calls oiBHTScheduleGrossWeightSent which Updates Row in SQL Server to Mark Success/Failure -->
									<![CDATA[EXEC dbo.oiBHTScheduleGrossWeightSent ?, ?]]>
									<params>
										<param name="OI_EventID" source=".OI_EventID" type="adinteger" direction="adparaminput"/>
										<param name="OracleReturnCode" source="RETURN_CODE" type="adinteger" direction="adparaminput"/>
									</params>
									<foreach/>
								</command>
							</foreach>
						</command>
					</foreach>
				</command>
			</step>
<!--SEGMENT EVENTS GO HERE -->
			<step name="Download Production Schedule Queue">
				<command name="Get Cost Centers and PICSIDs From SQL" rowset="true" connid="SQL" begintran="false" enabled="true">
					<!--This Command calls oiBHTGetCCDefs which Retrieves Rowset Containing PICSID, CCID, and CCKey Values for Each Cost Center to Be Synchronized -->
					<![CDATA[EXEC dbo.oiBHTGetCCDefs]]>
					<params/>
					<foreach>
						<command name="Start Cost Center Download" rowset="false" begintran="false" connid="SQL" enabled="true">
							<!--This Command calls oiBHTSchedCCDownloadStart which Initializes Cost Center for Download -->
							<![CDATA[EXEC dbo.oiBHTSchedCCDownloadStart ?]]>
							<params>
								<param name="CCKey" source="CCKey" type="adchar" direction="adparaminput" size="5"/>
							</params>
							<foreach/>
						</command>
						<command name="Get Cost Center Schedule From Oracle" rowset="true" connid="ORACLE" begintran="false" enabled="true">
							<!--This Command calls qdaq$PK_SCHEDULE_IQ_PLC.GetQueue which retrieves data from Oracle -->
							<![CDATA[{call qdaq$PK_SCHEDULE_IQ_PLC.GetQueue (?, ?)}]]>
							<params>
								<param name="al_PicsID" source="PICSID" type="adinteger" direction="adparaminput"/>
								<param name="al_CC" source="CCID" type="adinteger" direction="adparaminput"/>
							</params>
							<foreach>
								<command name="Load Schedule Entry Into SQL" rowset="false" connid="SQL" begintran="false" enabled="true">
									<!--This Command calls oiBHTSchedCCDownloadSchedItem which Loads Individual Schedule Entry Into SQL -->
									<![CDATA[EXEC dbo.oiBHTSchedCCDownloadSchedItem ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?]]>
									<params>
										<param name="EquipID" source="EQUIPMENT_ID" type="adinteger" direction="adparaminput"/>
										<param name="ScheduleID" source="SCHEDULE_SEQ_ID" type="adinteger" direction="adparaminput"/>
